apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-resource-limits
  annotations:
    policies.kyverno.io/title: Enforce resource limits
    policies.kyverno.io/category: Best Practices
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-limits-and-requests
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      validate:
        message: "All containers must define CPU and memory requests/limits."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - name: "*"
                    resources:
                      requests:
                        memory: "?*"
                        cpu: "?*"
                      limits:
                        memory: "?*"
                        cpu: "?*"
